# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Default


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'eightNew'
    browserstackLocal: true
    bsLocalOptions: '{"localIdentifier":"abcdefgh-8-11"}'

- script: |
    npm install
  displayName: 'npm install'
  
- task: BrowserStackStopLocal@0
  inputs:
    localIdentifier: 'abcdefgh-0-11'
